### ISSUE TITLE
Possible bug (?) in system accuracy comparison

### ISSUE THREAD

**Issue by ahoho** [MicrosoftTranslator/ToShipOrNotToShip#3]
Sorry for creating another issue, but figured this was worth clarifying. 

I was trying to write my own version of the accuracy comparison and noticed that when comparing automatic metrics, you have the following: 
https://github.com/MicrosoftTranslator/ToShipOrNotToShip/blob/bac575a47a5dcdd50f15d1f1dd6d0323503bc789/evaluation/analysis.py#L80-L82

In some cases, `automatic_metrics` appear to have been calculated over more examples than the `hum_annotations` (e.g. campaign `0001119f8b0cf0a4c8ac7bf2d9a21381` and system `e71a78d7eb257e0bc76f4b2694369e94` has 984 annotations, but `automatic_metrics` is over 1997). There is another dictionary titled  `human_only_automated_metrics` that appears to calculate metrics for the the same set of annotated examples---should this be used instead, when it's available?

Apologies if I've gotten something wrong!

**Comment by kocmitom** [comment]
This is not a bug, but poorly described data (I will do a better job after vacation, I am really sorry for that).

In short: when doing human evaluation in MT we usually have large testset for automatic evaluation, let's say 2000 sentences. Since humans do not need to evaluate all sentences to differentiate two systems (and also because it would be expensive to run full testset evaluation) it is a common practice to subsample sentences for human evaluation.

But subsampled data could hurt metrics performance, therefore the difference in metrics is calculated over all sentences in the testset, while human evaluation only over sentences evaluated by humans. You can simply change the script and evaluate on the same subset, when I was experimenting with it, I haven't seen a significant difference in final results (ranking of metrics was similar).

I hope it clarified it a bit.

**Comment by ahoho** [comment]
Yes, this was very helpful and makes perfect sense, thanks for responding while on vacation! I'll close this now.
